spring:
  profiles:
    default: dev

  application:
    name: collector

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      retry:
        max-interval: 6000
        max-attempts: 5