aggregator:
  kafka-producer:
    topic: "telemetry.snapshots.v1"
    properties:
      bootstrap.servers: "localhost:9092"
      key.serializer: "org.apache.kafka.common.serialization.VoidSerializer"
      value.serializer: "ru.yandex.practicum.kafka.serializer.BaseAvroSerializer"
      enable.auto.commit: "true"

  kafka-consumer:
    topic: "telemetry.sensors.v1"
    properties:
      max.poll.interval.ms: 300000 # 5 минут
      session.timeout.ms: 10000
      heartbeat.interval.ms: 3000
      auto.offset.reset: "earliest"
      auto.commit.interval.ms: "1000"
      bootstrap.servers: "localhost:9092"
      group.id: "aggregator-group"
      key.deserializer: "org.apache.kafka.common.serialization.VoidDeserializer"
      value.deserializer: "ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer"
      enable.auto.commit: "true"